# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commericalinvoice',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerical_invoice_billing', to='card.billing'),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='commerical_invoice_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerical_invoice_customer', to='card.company'),
        ),
    ]
