# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_initial'),
        ('sale', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commericalinvoice',
            name='orderTracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerical_invoice_order_tracking', to='sale.ordertracking'),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerical_invoice', to='sale.project'),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerical_invoice_seller', to='source.company'),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerical_invoice_source_company', to='source.company'),
        ),
    ]
