# Generated by Django 5.0.4 on 2025-08-18 20:54

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_initial'),
        ('card', '0003_initial'),
        ('data', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sale', '0002_initial'),
        ('service', '0001_initial'),
        ('source', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commericalinvoice',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerical_invoice_request', to='sale.request'),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commericalinvoice',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerical_invoice_vessel', to='card.vessel'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceexpense',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.expense'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceexpense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commericalinvoice'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceexpense',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerical_invoice_expense_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerical_invoice_expense', to='data.expense'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.commericalinvoice'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='offerServiceCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerical_invoice_offer_service_card', to='service.offerservicecard'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerical_invoice_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='quotationPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commerical_invoice_quotation_part', to='sale.quotationpart'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='serviceCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerical_invoice_service_card', to='data.servicecard'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerical_invoice_item_ource_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='commericalinvoiceitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='incoming_invoice_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_invoice_customer', to='card.company'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='customerSource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_invoice_customer_source', to='source.company'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice', to='sale.project'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice_purchase_order', to='sale.purchaseorder'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='purchasingProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_incoming_invoice', to='purchasing.project'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='purchasingPurchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchasing_incoming_invoice_purchase_order', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_invoice_seller', to='card.company'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice_request', to='sale.request'),
        ),
        migrations.AddField(
            model_name='incominginvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incominginvoiceexpense',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.expense'),
        ),
        migrations.AddField(
            model_name='incominginvoiceexpense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.incominginvoice'),
        ),
        migrations.AddField(
            model_name='incominginvoiceexpense',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice_expense_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='incominginvoiceexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoice_expense', to='data.expense'),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.incominginvoice'),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoice_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='purchaseOrderPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='incoming_invoice_purchase_order_part', to='sale.purchaseorderpart'),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='purchasingPurchaseOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchasing_incoming_invoice_purchase_order_item', to='purchasing.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice_item_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='incominginvoiceitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incominginvoicepart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.incominginvoice'),
        ),
        migrations.AddField(
            model_name='incominginvoicepart',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoice_part_manuel_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='incominginvoicepart',
            name='purchaseOrderPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_invoice_part_part', to='sale.purchaseorderpart'),
        ),
        migrations.AddField(
            model_name='incominginvoicepart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_invoice_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='incominginvoicepart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='payment_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment_customer', to='card.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sourceBank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_source_bank', to='source.bank'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='incomingInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoice_incoming_invoice', to='account.incominginvoice'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.payment'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_invoice_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='process',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='process_customer', to='card.company'),
        ),
        migrations.AddField(
            model_name='process',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='process_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='process',
            name='incomingInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_incoming_invoice', to='account.incominginvoice'),
        ),
        migrations.AddField(
            model_name='process',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_payment', to='account.payment'),
        ),
        migrations.AddField(
            model_name='process',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='process',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processstatus',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_status_offer', to='service.offer'),
        ),
        migrations.AddField(
            model_name='processstatus',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_status_project', to='sale.project'),
        ),
        migrations.AddField(
            model_name='processstatus',
            name='purchasingProject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_status_purchasing_project', to='purchasing.project'),
        ),
        migrations.AddField(
            model_name='processstatus',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_status_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='processstatus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_billing', to='card.billing'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='proforma_invoice_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_customer', to='card.company'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_offer', to='service.offer'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='orderConfirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_order_confirmation', to='sale.orderconfirmation'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice', to='sale.project'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_seller', to='source.company'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_request', to='sale.request'),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proformainvoice',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_vessel', to='card.vessel'),
        ),
        migrations.AddField(
            model_name='proformainvoiceexpense',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.expense'),
        ),
        migrations.AddField(
            model_name='proformainvoiceexpense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformainvoiceexpense',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_exepnse_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='proformainvoiceexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoice_expense', to='data.expense'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='offerExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_offer_expense', to='service.offerexpense'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='offerPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_offer_part', to='service.offerpart'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='offerServiceCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_offer_service_card', to='service.offerservicecard'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoice_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='quotationPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proforma_invoice_quotation_part', to='sale.quotationpart'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='serviceCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoice_service_card', to='data.servicecard'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_item_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='proformainvoiceitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proformainvoicepart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.proformainvoice'),
        ),
        migrations.AddField(
            model_name='proformainvoicepart',
            name='quotationPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoice_part_part', to='sale.quotationpart'),
        ),
        migrations.AddField(
            model_name='proformainvoicepart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proforma_invoice_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='proformainvoicepart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='billing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_billing', to='card.billing'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='send_invoice_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_customer', to='card.company'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_offer', to='service.offer'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='orderConfirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_order_confirmation', to='sale.orderconfirmation'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice', to='sale.project'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_seller', to='source.company'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_request', to='sale.request'),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendinvoice',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_vessel', to='card.vessel'),
        ),
        migrations.AddField(
            model_name='process',
            name='sendInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_send_invoice', to='account.sendinvoice'),
        ),
        migrations.AddField(
            model_name='paymentinvoice',
            name='sendInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_invoice_send_invoice', to='account.sendinvoice'),
        ),
        migrations.AddField(
            model_name='sendinvoiceexpense',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.expense'),
        ),
        migrations.AddField(
            model_name='sendinvoiceexpense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sendinvoice'),
        ),
        migrations.AddField(
            model_name='sendinvoiceexpense',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_expense_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='sendinvoiceexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_invoice_expense', to='data.expense'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sendinvoice'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='offerExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_offer_expense', to='service.offerexpense'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='offerPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_offer_part', to='service.offerpart'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='offerServiceCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_offer_service_card', to='service.offerservicecard'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_invoice_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='quotationExpense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_quotation_expense', to='sale.quotationextra'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='quotationPart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='send_invoice_quotation_part', to='sale.quotationpart'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='serviceCard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_invoice_service_card', to='data.servicecard'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_item_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='sendinvoiceitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendinvoicepart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sendinvoice'),
        ),
        migrations.AddField(
            model_name='sendinvoicepart',
            name='quotationPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_invoice_part_part', to='sale.quotationpart'),
        ),
        migrations.AddField(
            model_name='sendinvoicepart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='sendinvoicepart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sendinvoiceservicecard',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sendinvoice'),
        ),
        migrations.AddField(
            model_name='sendinvoiceservicecard',
            name='offerServiceCard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_invoice_partt_part', to='service.offerservicecard'),
        ),
        migrations.AddField(
            model_name='sendinvoiceservicecard',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_service_car_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='sendinvoiceservicecard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesendinvoice',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='service_send_invoice_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='servicesendinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_send_invoice_customer', to='card.company'),
        ),
        migrations.AddField(
            model_name='servicesendinvoice',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_invoice_request', to='service.offer'),
        ),
        migrations.AddField(
            model_name='servicesendinvoice',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='service_send_invoice_seller', to='card.company'),
        ),
        migrations.AddField(
            model_name='servicesendinvoice',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_send_invoce_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='servicesendinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceexpense',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.servicesendinvoice'),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceexpense',
            name='offerExpense',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_send_invoice_expense_expense', to='service.offerexpense'),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceexpense',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_send_invoice_expense_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceexpense',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesendinvoicepart',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.servicesendinvoice'),
        ),
        migrations.AddField(
            model_name='servicesendinvoicepart',
            name='offerPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_send_invoice_expense_expense', to='service.offerpart'),
        ),
        migrations.AddField(
            model_name='servicesendinvoicepart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_send_invoice_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='servicesendinvoicepart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceservicecard',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.servicesendinvoice'),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceservicecard',
            name='offerServiceCard',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_send_invoice_service_card_service_card', to='service.offerservicecard'),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceservicecard',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_send_invoice_service_card_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='servicesendinvoiceservicecard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(account.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='incominginvoicepart',
            constraint=models.UniqueConstraint(fields=('purchaseOrderPart', 'invoice'), name='unique_purchaseOrderPart_invoice'),
        ),
        migrations.AddConstraint(
            model_name='proformainvoicepart',
            constraint=models.UniqueConstraint(fields=('quotationPart', 'invoice'), name='unique_quotationPart_proforma_invoice'),
        ),
        migrations.AddConstraint(
            model_name='sendinvoicepart',
            constraint=models.UniqueConstraint(fields=('quotationPart', 'invoice'), name='unique_quotationPart_invoice'),
        ),
        migrations.AddConstraint(
            model_name='servicesendinvoiceexpense',
            constraint=models.UniqueConstraint(fields=('offerExpense', 'invoice'), name='unique_offerExpense_invoice'),
        ),
        migrations.AddConstraint(
            model_name='servicesendinvoicepart',
            constraint=models.UniqueConstraint(fields=('offerPart', 'invoice'), name='unique_offerPart_invoice'),
        ),
        migrations.AddConstraint(
            model_name='servicesendinvoiceservicecard',
            constraint=models.UniqueConstraint(fields=('offerServiceCard', 'invoice'), name='unique_offerServiceCard_invoice'),
        ),
    ]
