# Generated by Django 5.0.4 on 2025-08-18 20:54

import administration.models
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=140, null=True, unique=True, verbose_name='Code')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(administration.models.get_sentinel_user), related_name='source_company_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=30, null=True)),
                ('modelName', models.CharField(blank=True, max_length=140, null=True, verbose_name='Model Name')),
                ('objectId', models.IntegerField(blank=True, null=True, verbose_name='Object Id')),
                ('objectName', models.CharField(blank=True, null=True, verbose_name='Object Name')),
                ('actionLogDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Action Log Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(administration.models.get_sentinel_user), related_name='action_log_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=140, null=True, unique=True, verbose_name='Code')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(administration.models.get_sentinel_user), related_name='administration_data_authorization_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
