# Generated by Django 5.0.4 on 2025-08-18 20:54

import data.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('source', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Excel File')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_source_company', to='source.company')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Expense Name')),
                ('code', models.CharField(max_length=140, verbose_name='Expense Code')),
                ('group', models.CharField(blank=True, max_length=140, null=True, verbose_name='Expense Group')),
                ('unit', models.CharField(choices=[('day', 'Day'), ('hrs', 'HRS'), ('kg', 'Kg'), ('m²', 'm²'), ('mm', 'MM'), ('pc', 'Pc'), ('pcs', 'PCS'), ('pk', 'PK'), ('persons', 'Persons')], default='pc', max_length=40, verbose_name='Units')),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_source_company', to='source.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Maker Name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('type', models.JSONField(blank=True, null=True, verbose_name='Type')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_source_company', to='source.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MakerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Maker Type Name')),
                ('type', models.CharField(max_length=140, verbose_name='Type')),
                ('note', models.CharField(blank=True, max_length=140, null=True, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maker_type_maker', to='data.maker')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maker_type_source_company', to='source.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partUniqueCode', models.IntegerField(blank=True, null=True, verbose_name='Part Unique Code')),
                ('group', models.CharField(blank=True, max_length=140, null=True, verbose_name='Group')),
                ('unit', models.CharField(choices=[('day', 'Day'), ('hrs', 'HRS'), ('kg', 'Kg'), ('m²', 'm²'), ('mm', 'MM'), ('pc', 'Pc'), ('pcs', 'PCS'), ('pk', 'PK'), ('persons', 'Persons')], default='pc', max_length=40, verbose_name='Units')),
                ('description', models.TextField(blank=True, db_index=True, max_length=250, verbose_name='Description')),
                ('partNo', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Part No')),
                ('manufacturer', models.CharField(blank=True, max_length=140, null=True, verbose_name='Manufacturer')),
                ('drawingNr', models.CharField(blank=True, max_length=140, null=True, verbose_name='Drawing Nr')),
                ('techncialSpecification', models.CharField(blank=True, max_length=140, null=True, verbose_name='Techncial Specification')),
                ('consumable', models.BooleanField(default=True, verbose_name='Consumable')),
                ('crossRef', models.CharField(blank=True, max_length=140, null=True, verbose_name='Cross Ref')),
                ('ourRef', models.CharField(blank=True, max_length=140, null=True, verbose_name='Our Ref')),
                ('barcode', models.CharField(blank=True, max_length=140, null=True, verbose_name='Barcode')),
                ('hsCode', models.CharField(blank=True, max_length=140, null=True, verbose_name='HS Code')),
                ('buyingPrice', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Buying Prince')),
                ('retailPrice', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Retail Price')),
                ('dealerPrice', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Dealer Price')),
                ('wholesalePrice', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Wholesale Price')),
                ('weight', models.CharField(blank=True, max_length=140, null=True, verbose_name='Weight')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('image', models.ImageField(blank=True, null=True, upload_to=data.models.part_directory_path, verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(default=106, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='curency_for_part', to='card.currency')),
                ('maker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_maker', to='data.maker')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_source_company', to='source.company')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_maker_type', to='data.makertype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(data.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('image', models.ImageField(blank=True, null=True, upload_to=data.models.part_image_directory_path, verbose_name='Image')),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.part')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_image_source_company', to='source.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(data.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartUnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', data.models.UniqueAutoIncrementField()),
                ('description', models.CharField(blank=True, max_length=140, null=True, verbose_name='Description')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_unique_source_company', to='source.company')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='partUnique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_unique', to='data.partunique'),
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineType', models.CharField(blank=True, choices=[('2-zamanli', '2 Zamanlı'), ('4-zamanli', '4 Zamanlı'), ('genel', 'Genel')], max_length=40, null=True, verbose_name='Machine Types')),
                ('name', models.CharField(max_length=140, verbose_name='Service Name')),
                ('code', models.CharField(max_length=140, verbose_name='Service Code')),
                ('group', models.CharField(blank=True, max_length=140, null=True, verbose_name='Service Group')),
                ('unit', models.CharField(choices=[('day', 'Day'), ('hrs', 'HRS'), ('kg', 'Kg'), ('m²', 'm²'), ('mm', 'MM'), ('pc', 'Pc'), ('pcs', 'PCS'), ('pk', 'PK'), ('persons', 'Persons')], default='pc', max_length=40, verbose_name='Units')),
                ('quantity', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Quantity')),
                ('about', models.TextField(blank=True, null=True, verbose_name='about')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_card_source_company', to='source.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
