# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
import django.utils.timezone
import warehouse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sale', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('identificationCode', models.CharField(blank=True, default='I', max_length=140, null=True, verbose_name='Identification Code')),
                ('dateCode', models.CharField(blank=True, max_length=140, null=True, verbose_name='Date Code')),
                ('code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Item Code')),
                ('itemNo', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Item No')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Location')),
                ('category', models.CharField(blank=True, max_length=140, null=True, verbose_name='Category')),
                ('unit', models.CharField(choices=[('day', 'Day'), ('hrs', 'HRS'), ('kg', 'Kg'), ('m²', 'm²'), ('mm', 'MM'), ('pc', 'Pc'), ('pcs', 'PCS'), ('pk', 'PK'), ('persons', 'Persons')], default='pc', max_length=40, verbose_name='Units')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('barcode', models.CharField(blank=True, max_length=140, null=True, verbose_name='Barcode')),
                ('buyingPrice', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Buying Prince')),
                ('cost', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Cost')),
                ('salePrice', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Sale Price')),
                ('vat', models.FloatField(blank=True, default=0, null=True, verbose_name='Vat')),
                ('weight', models.FloatField(blank=True, default=0, null=True, verbose_name='Weight')),
                ('width', models.FloatField(blank=True, default=0, null=True, verbose_name='Weight')),
                ('height', models.FloatField(blank=True, default=0, null=True, verbose_name='Weight')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('image', models.ImageField(blank=True, null=True, upload_to=warehouse.models.part_directory_path, verbose_name='Logo')),
                ('itemDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Item Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('category', models.CharField(blank=True, max_length=140, null=True, verbose_name='Category')),
                ('unit', models.CharField(choices=[('day', 'Day'), ('hrs', 'HRS'), ('kg', 'Kg'), ('m²', 'm²'), ('mm', 'MM'), ('pc', 'Pc'), ('pcs', 'PCS'), ('pk', 'PK'), ('persons', 'Persons')], default='pc', max_length=40, verbose_name='Units')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('barcode', models.CharField(blank=True, max_length=140, null=True, verbose_name='Barcode')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Quantity')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('image', models.ImageField(blank=True, null=True, upload_to=warehouse.models.part_directory_path, verbose_name='Logo')),
                ('itemGroupDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Item Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Item Code')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='Name')),
                ('address', models.TextField(blank=True, max_length=150, null=True, verbose_name='Address')),
                ('phone1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('phone3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('phone4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('phone5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax 1')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('identificationCode', models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='Identification Code')),
                ('yearCode', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dispatch  Year')),
                ('code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Dispatch  Code')),
                ('dispatchNo', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Dispatch  No')),
                ('dispatchDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Dispatch  Date')),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='Note')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_project', to='sale.project')),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_source_company', to='source.company')),
            ],
            options={
                'ordering': ['dispatchDate'],
            },
        ),
    ]
