# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
import warehouse.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_initial'),
        ('card', '0003_initial'),
        ('data', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('sale', '0002_initial'),
        ('source', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_request', to='sale.request'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(warehouse.models.get_sentinel_user), related_name='dispatch_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(default=106, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='item_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='item',
            name='incomingInvoiceItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_incoming_invoice_item', to='account.incominginvoiceitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchaseOrderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_purchase_order_item', to='purchasing.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='item',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(warehouse.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_group_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_group_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(warehouse.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='itemGroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_item_group', to='warehouse.itemgroup'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_city', to='card.city'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='warehouse_country', to='card.country'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(warehouse.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_group_warehouse', to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_warehouse', to='warehouse.warehouse'),
        ),
    ]
