# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.core.validators
import django.db.models.deletion
import utilities.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakerTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Category Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Unit Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Maker Name')),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ManyToManyField(to='parts.makercategory')),
            ],
        ),
        migrations.CreateModel(
            name='MakerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/makers/', validators=[utilities.validators.ExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parts.maker')),
            ],
        ),
        migrations.CreateModel(
            name='MakerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Maker Type Name')),
                ('type', models.CharField(max_length=140, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maker_types', to='parts.maker')),
                ('category', models.ManyToManyField(to='parts.makertypecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MakerTypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/maker_types/', validators=[utilities.validators.ExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maker_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parts.makertype')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, unique=True, verbose_name='Manufacturer Name')),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ManyToManyField(related_name='manufacturers', to='parts.makercategory', verbose_name='Category')),
                ('maker', models.ManyToManyField(related_name='manufacturers', to='parts.maker', verbose_name='Maker (Compatible)')),
                ('maker_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_info', to='parts.maker', verbose_name='Maker')),
                ('supplier_info', models.ForeignKey(blank=True, limit_choices_to=models.Q(('company_type__contains', 'Supplier')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_info', to='information.company', verbose_name='Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Part Name')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('code', models.CharField(max_length=140, unique=True, verbose_name='Part Code')),
                ('dimensions', models.CharField(blank=True, max_length=140, verbose_name='Dimensions')),
                ('material', models.CharField(blank=True, max_length=140, verbose_name='Material')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.partcategory', verbose_name='Category')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='parts.partunit', verbose_name='Unit')),
            ],
        ),
        migrations.CreateModel(
            name='PartDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/parts/', validators=[utilities.validators.ExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parts.part')),
            ],
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/parts/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.part')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Related Set Name')),
                ('code', models.CharField(max_length=140, unique=True, validators=[django.core.validators.RegexValidator('ES-SET-\\d+', message='You should use this format: ES-SET-X')], verbose_name='Related Set Code')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('parts', models.ManyToManyField(related_name='sets', to='parts.part', verbose_name='Parts')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedSetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/related_sets/', validators=[utilities.validators.ExtensionValidator(['pdf', 'doc', 'docx'])], verbose_name='Document')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('related_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parts.relatedset')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedSetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/related_sets/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('related_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='parts.relatedset')),
            ],
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, verbose_name='Maker Part Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.maker')),
                ('maker_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.makertype')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='parts.part')),
            ],
            options={
                'unique_together': {('part', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PartManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, verbose_name='Manufacturer Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.manufacturer')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturers', to='parts.part')),
            ],
            options={
                'unique_together': {('part', 'code')},
            },
        ),
        migrations.CreateModel(
            name='PartSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=140, verbose_name='Supplier Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='parts.part')),
                ('supplier', models.ForeignKey(limit_choices_to=models.Q(('company_type__contains', 'Supplier')), null=True, on_delete=django.db.models.deletion.CASCADE, to='information.company', verbose_name='Supplier')),
            ],
            options={
                'unique_together': {('part', 'code')},
            },
        ),
    ]
