# Generated by Django 5.0.4 on 2025-08-18 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Bank Name')),
                ('translation_type', models.CharField(choices=[('IBAN', 'IBAN'), ('SWIFT', 'SWIFT')], default='IBAN', max_length=50)),
                ('iban', models.CharField(blank=True, max_length=34, null=True, verbose_name='IBAN')),
                ('swift', models.CharField(blank=True, max_length=11, null=True, verbose_name='Swift')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TheCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('url', models.URLField(verbose_name='url')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('address_2', models.TextField(blank=True, verbose_name='Address 2')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Tax ID')),
                ('tax_office', models.CharField(blank=True, max_length=100, verbose_name='Tax Office')),
                ('kep_address', models.EmailField(blank=True, max_length=254)),
                ('mersis_no', models.CharField(blank=True, max_length=16, verbose_name='MERSIS No')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('phone_number_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number 2')),
                ('fax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax Number')),
                ('fax_number_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax Number 2')),
                ('legal_warning_text', models.TextField(blank=True, verbose_name='Legal Warning')),
                ('logo', models.ImageField(null=True, upload_to='images/logo/', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
