# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('source', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('allDay', models.BooleanField(default=True, verbose_name='All Day')),
                ('startDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Start Date')),
                ('endDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='End Date')),
                ('startTime', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='Start Time')),
                ('endTime', models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='End Time')),
                ('color', models.CharField(blank=True, choices=[('cfe0fc', '#cfe0fc'), ('ebcdfe', '#ebcdfe'), ('c7f5d9', '#c7f5d9'), ('fdd8de', '#fdd8de'), ('ffebc2', '#ffebc2'), ('d0f0fb', '#d0f0fb'), ('292929', '#292929')], default='cfe0fc', max_length=40, null=True, verbose_name='Color')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('sourceCompany', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_source_company', to='source.company')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
