# Generated by Django 5.0.4 on 2025-08-18 20:54

import card.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0002_initial'),
        ('data', '0001_initial'),
        ('source', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='satisTemsilcisi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='satis_temsilcisi', to='user.profile'),
        ),
        migrations.AddField(
            model_name='company',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.company'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='card.country'),
        ),
        migrations.AddField(
            model_name='billing',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.country'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curency_2', to='card.currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curency_3', to='card.currency'),
        ),
        migrations.AddField(
            model_name='billing',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_curency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='billing',
            name='currency2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_curency_2', to='card.currency'),
        ),
        migrations.AddField(
            model_name='billing',
            name='currency3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_curency_3', to='card.currency'),
        ),
        migrations.AddField(
            model_name='bank',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='current',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='current_company', to='card.company'),
        ),
        migrations.AddField(
            model_name='current',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='current_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='current',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='enginepart',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_part_maker', to='data.maker'),
        ),
        migrations.AddField(
            model_name='enginepart',
            name='makerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_part_type', to='data.makertype'),
        ),
        migrations.AddField(
            model_name='enginepart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_part_ssource_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='enginepart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(card.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='excel',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_excel_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.company'),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.company'),
        ),
        migrations.AddField(
            model_name='historicalvessel',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='source.company'),
        ),
        migrations.AddField(
            model_name='owner',
            name='ownerCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_company', to='card.company'),
        ),
        migrations.AddField(
            model_name='owner',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='person',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vessel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='company', to='card.company'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to='card.company'),
        ),
        migrations.AddField(
            model_name='vessel',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vessel_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='person',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.vessel'),
        ),
        migrations.AddField(
            model_name='owner',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_vessel', to='card.vessel'),
        ),
        migrations.AddField(
            model_name='enginepart',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.vessel'),
        ),
        migrations.AddField(
            model_name='billing',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_vessel', to='card.vessel'),
        ),
    ]
