# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.core.validators
import django.db.models.deletion
import utilities.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(blank=True, max_length=50, null=True, verbose_name='Base')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('rate', models.DecimalField(decimal_places=10, default=1.0, max_digits=30, verbose_name='Rate')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='beta_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(help_text='Please upload a square image, otherwise center will be cropped.', null=True, upload_to='images/profiles/', verbose_name='Image')),
                ('birthday', models.DateField(null=True, verbose_name='Birthday')),
                ('birthplace', models.CharField(max_length=120, null=True, verbose_name='Birth Place')),
                ('phone_number', models.CharField(max_length=50, null=True, verbose_name='Phone Number')),
                ('home_number', models.CharField(max_length=50, null=True, verbose_name='Home Number')),
                ('address', models.TextField(null=True, verbose_name='Address')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1, null=True)),
                ('marial_status', models.CharField(choices=[('m', 'Married'), ('s', 'Single')], max_length=1, null=True)),
                ('compulsory_military_service_status', models.CharField(blank=True, choices=[('e', 'Exempt'), ('c', 'Completed'), ('dl', 'Delayed for less than 2 years'), ('dm', 'Delayed for more than 2 years')], max_length=2, null=True)),
                ('degree', models.CharField(max_length=100, null=True, verbose_name='Degree')),
                ('total_annual_leave', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Annual Leave')),
                ('remaining_annual_leave', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Remaining Annual Leave')),
                ('salary', models.DecimalField(decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Salary')),
                ('bonus_right', models.BooleanField(default=False, verbose_name='Bonus Right')),
                ('bonus_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='Bonus Rate %')),
                ('bonus_info', models.TextField(null=True, verbose_name='Bonus Information')),
                ('language', models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='Turkish', max_length=50, verbose_name='Language')),
                ('theme', models.CharField(choices=[('dark', 'Dark'), ('light', 'Light')], default='dark', max_length=25, verbose_name='Theme')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_members', to='beta_profile.department')),
                ('employee_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_members', to='beta_profile.employeetype')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_members', to='beta_profile.title')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick'), ('holiday', 'Holiday'), ('unpaid', 'Unpaid Leave'), ('other', 'Other')], default='other', max_length=8, verbose_name='Leave Type')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Pending', 'Pending'), ('Canceled', 'Canceled')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='beta_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Fixture Name')),
                ('brand', models.CharField(max_length=255, verbose_name='Brand')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Serial Number')),
                ('current_situtation', models.TextField(blank=True, null=True, verbose_name='Current Situtation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='beta_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Institution Name')),
                ('education_level', models.CharField(choices=[('ps', 'Primary School'), ('ss', 'Secondary School'), ('hh', 'High School'), ('hhd', 'High School (Distance Education)'), ('adeg', 'Associate Degree'), ('adegd', 'Associate Degree (Distance Education)'), ('deg', 'Degree'), ('degd', 'Degree (Distance Education)'), ('mdeg', 'Master Degree'), ('doc', 'Doctorate')], max_length=5, verbose_name='Education Level')),
                ('major', models.CharField(default='Compulsory Education', max_length=255, verbose_name='Major Branch')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='documents/hr/diploma', validators=[utilities.validators.ExtensionValidator(['pdf'])], verbose_name='Diploma')),
                ('is_completed', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='beta_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Certificate Name')),
                ('issued_by', models.CharField(max_length=255, verbose_name='Issued By')),
                ('issued_date', models.DateField(verbose_name='Issued Date')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='Expired Date')),
                ('file', models.FileField(upload_to='documents/hr/certification', validators=[utilities.validators.ExtensionValidator(['pdf', 'png'])], verbose_name='CV / Resume')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_certifications', to='beta_profile.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=256)),
                ('username', models.CharField(max_length=150, null=True)),
                ('path', models.TextField(null=True)),
                ('query_string', models.TextField(blank=True, null=True)),
                ('method', models.CharField(max_length=7)),
                ('secure', models.BooleanField(default=False)),
                ('ajax', models.BooleanField(default=False)),
                ('meta', models.TextField(blank=True, null=True)),
                ('address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_code', models.CharField(max_length=3)),
                ('response_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Records',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True, unique=True, verbose_name='Name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='beta_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('file', models.FileField(upload_to='documents/hr/user_document', validators=[utilities.validators.ExtensionValidator(['pdf'])], verbose_name='Document')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='beta_profile.profile')),
            ],
            options={
                'unique_together': {('profile', 'title')},
            },
        ),
    ]
