# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
import django.utils.timezone
import sale.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0003_initial'),
        ('data', '0001_initial'),
        ('sale', '0001_initial'),
        ('source', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchorder',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
        migrations.AddField(
            model_name='dispatchorderpart',
            name='collectionPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_order_part_part', to='sale.collectionpart'),
        ),
        migrations.AddField(
            model_name='dispatchorderpart',
            name='dispatchOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.dispatchorder'),
        ),
        migrations.AddField(
            model_name='dispatchorderpart',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatch_order_part_maker', to='data.maker'),
        ),
        migrations.AddField(
            model_name='dispatchorderpart',
            name='makerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dispatch_order_part_maker_type', to='data.makertype'),
        ),
        migrations.AddField(
            model_name='dispatchorderpart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_order_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='dispatchorderpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='inquiry_part_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.person'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.company'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), related_name='inquiry_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.inquiry'),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inquiry_part_maker', to='data.maker'),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='makerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inquiry_part_maker_type', to='data.makertype'),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquriy_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_confirmation_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), related_name='order_confirmation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='orderConfirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.orderconfirmation'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='orderConfirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.orderconfirmation'),
        ),
        migrations.AddField(
            model_name='ordernotconfirmation',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_notconfirmation_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tracking_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), related_name='order_tracking_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatchorder',
            name='orderTracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ordertracking'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='orderTracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ordertracking'),
        ),
        migrations.AddField(
            model_name='collection',
            name='orderTracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ordertracking'),
        ),
        migrations.AddField(
            model_name='ordertrackingdocument',
            name='orderTracking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.ordertracking'),
        ),
        migrations.AddField(
            model_name='ordertrackingdocument',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tracking_document_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='ordertrackingdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('project', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='request', serialize=False, to='sale.project')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('identificationCode', models.CharField(blank=True, default='', max_length=140, null=True, verbose_name='Identification Code')),
                ('yearCode', models.CharField(blank=True, max_length=140, null=True, verbose_name='Request Year')),
                ('code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Request Code')),
                ('requestNo', models.CharField(blank=True, db_index=True, max_length=140, null=True, verbose_name='Request No')),
                ('customerRef', models.CharField(blank=True, max_length=140, null=True, verbose_name='Customer Ref')),
                ('note', models.CharField(blank=True, max_length=150, null=True, verbose_name='Note')),
                ('requestDate', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Request Date')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['requestDate'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking', to='sale.project'),
        ),
        migrations.AddField(
            model_name='ordernotconfirmation',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_not_confirmation', to='sale.project'),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmation', to='sale.project'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='sale.project'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='purchase_order_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_inquiry', to='sale.inquiry'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='orderConfirmation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_order_confirmation', to='sale.orderconfirmation'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='sale.project'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), related_name='purchase_order_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='order_trackings', through='sale.Collection', to='sale.purchaseorder'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='purchaseOrders',
            field=models.ManyToManyField(blank=True, related_name='purchase_orders', to='sale.purchaseorder'),
        ),
        migrations.AddField(
            model_name='collection',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='inquiryPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseOrder_part_part', to='sale.inquirypart'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchaseOrder_part_maker', to='data.maker'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='makerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchaseOrder_part_maker_type', to='data.makertype'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='purchaseOrder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='purchaseOrders', through='sale.PurchaseOrderPart', to='sale.inquirypart'),
        ),
        migrations.AddField(
            model_name='collectionpart',
            name='purchaseOrderPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_part_part', to='sale.purchaseorderpart'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.ForeignKey(blank=True, default=106, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='quotation_part_currency', to='card.currency'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inquiries',
            field=models.ManyToManyField(blank=True, related_name='inquiries', to='sale.inquiry'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_inquiry', to='sale.inquiry'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.person'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='sale.project'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), related_name='quotation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordernotconfirmation',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_not_confirmation_quotation', to='sale.quotation'),
        ),
        migrations.AddField(
            model_name='orderconfirmation',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_confirmation_quotation', to='sale.quotation'),
        ),
        migrations.AddField(
            model_name='quotationextra',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.quotation'),
        ),
        migrations.AddField(
            model_name='quotationextra',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_extra_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='quotationextra',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='inquiryPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotaiton_part_part', to='sale.inquirypart'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotation_part_maker', to='data.maker'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='makerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotation_part_maker_type', to='data.makertype'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.quotation'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='quotations', through='sale.QuotationPart', to='sale.inquirypart'),
        ),
        migrations.AddField(
            model_name='reason',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reason_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='ordernotconfirmation',
            name='reasons',
            field=models.ManyToManyField(blank=True, related_name='reasons', to='sale.reason'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_part_part', to='data.part'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_part_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(sale.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='requestPart',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_part_part', to='sale.requestpart'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='parts',
            field=models.ManyToManyField(blank=True, related_name='inquiries', through='sale.InquiryPart', to='sale.requestpart'),
        ),
        migrations.AddConstraint(
            model_name='dispatchorderpart',
            constraint=models.UniqueConstraint(fields=('collectionPart', 'dispatchOrder'), name='unique_collectionPart_dispatchOrder'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sale.request'),
        ),
        migrations.AddField(
            model_name='request',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='card.company'),
        ),
        migrations.AddField(
            model_name='request',
            name='maker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_maker', to='data.maker'),
        ),
        migrations.AddField(
            model_name='request',
            name='makerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_maker_type', to='data.makertype'),
        ),
        migrations.AddField(
            model_name='request',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.person'),
        ),
        migrations.AddField(
            model_name='request',
            name='sourceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_source_company', to='source.company'),
        ),
        migrations.AddField(
            model_name='request',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='card.vessel'),
        ),
        migrations.AddField(
            model_name='request',
            name='vesselPerson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_vessel_person', to='card.person'),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_tracking_request', to='sale.request'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='theRequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inquiry_request', to='sale.request'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('purchaseOrder', 'orderTracking'), name='unique_purchaseOrder_orderTracking'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderpart',
            constraint=models.UniqueConstraint(fields=('inquiryPart', 'purchaseOrder'), name='unique_inquiryPart_purchaseOrder'),
        ),
        migrations.AddConstraint(
            model_name='collectionpart',
            constraint=models.UniqueConstraint(fields=('purchaseOrderPart', 'collection'), name='unique_purchaseOrderPart_collection'),
        ),
        migrations.AddConstraint(
            model_name='inquirypart',
            constraint=models.UniqueConstraint(fields=('requestPart', 'inquiry'), name='unique_requestPart_inquiry'),
        ),
    ]
