# Generated by Django 5.0.4 on 2025-08-18 20:54

import ckeditor.fields
import django.db.models.deletion
import simple_history.models
import source.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('name', models.CharField(max_length=140, verbose_name='Company Name')),
                ('formalName', models.CharField(blank=True, max_length=140, null=True, verbose_name='Company Formal Name')),
                ('identificationCode', models.CharField(blank=True, default='SC', max_length=140, null=True, verbose_name='Identification Code')),
                ('code', models.CharField(blank=True, max_length=140, null=True, verbose_name='Company Code')),
                ('companyNo', models.CharField(blank=True, max_length=140, null=True, verbose_name='Company No')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('vatOffice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vat Office')),
                ('vatNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vat No')),
                ('phone1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('phone3', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('phone4', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('phone5', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone 2')),
                ('fax', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax 1')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('web', models.URLField(blank=True, max_length=100, null=True)),
                ('hesapKodu', models.CharField(blank=True, max_length=50, null=True, verbose_name='Hesap Kodu')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=source.models.company_directory_path, verbose_name='Logo')),
                ('documentLogo', models.ImageField(blank=True, null=True, upload_to=source.models.company_directory_path, verbose_name='Document Logo')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('saleRequestCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Request Code')),
                ('saleInquiryCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Inquiry Code')),
                ('saleQuotationCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Quotation Code')),
                ('saleOrderConfirmationCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Order Confirmation Code')),
                ('saleOrderNotConfirmationCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Order Not Confirmation Code')),
                ('salePurchaseOrderCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Purchase Order Code')),
                ('saleDispatchOrderCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Sale Dispatch Order Code')),
                ('serviceAcceptaneCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Service Acceptane Code')),
                ('serviceOfferCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Service Offer Code')),
                ('purchasingProjectCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Purchasing Project Code')),
                ('purchasingInquiryCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Purchasing Inquiry Code')),
                ('purchasingPurchaseOrderCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Purchasing Purchase Order Code')),
                ('accountIncomingInvoiceCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Account Incoming Invoice Code')),
                ('accountSendInvoiceCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Account Send Invoice Code')),
                ('accountProformaInvoiceCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Account Proforma Invoice Code')),
                ('accountCommercialInvoiceCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Account Commercial Invoice Code')),
                ('accountPaymentCode', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Account Payment Code')),
                ('sendInvoicePdfHtml', ckeditor.fields.RichTextField(blank=True, max_length=30000, null=True, verbose_name='Send Invoice Pdf Html')),
                ('mikroDBName', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Mikro DB Name')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_company_city', to='card.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_company_country', to='card.country')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.SET(source.models.get_sentinel_user), related_name='administration_access_authorization_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('bankName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank name')),
                ('accountNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account No')),
                ('ibanNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('accountType', models.CharField(choices=[('vadesiz', 'Vadesiz'), ('mevduat', 'Mevduat')], default='vadesiz', max_length=40, verbose_name='Type')),
                ('swiftNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift No')),
                ('branchName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch Name')),
                ('branchCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch Code')),
                ('balance', models.FloatField(blank=True, default=0, null=True, verbose_name='Balance')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_bank_currency', to='card.currency')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='source_bank_user', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='source.company')),
            ],
            options={
                'ordering': ['bankName'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBank',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sessionKey', models.CharField(blank=True, max_length=140, null=True, verbose_name='Session Key')),
                ('bankName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank name')),
                ('accountNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account No')),
                ('ibanNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('accountType', models.CharField(choices=[('vadesiz', 'Vadesiz'), ('mevduat', 'Mevduat')], default='vadesiz', max_length=40, verbose_name='Type')),
                ('swiftNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Swift No')),
                ('branchName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch Name')),
                ('branchCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Branch Code')),
                ('balance', models.FloatField(blank=True, default=0, null=True, verbose_name='Balance')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='source.company')),
                ('currency', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='card.currency')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
