# Generated by Django 5.0.4 on 2025-08-18 20:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('information', '0002_initial'),
        ('parts', '0001_initial'),
        ('sales', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='supplier',
            field=models.ForeignKey(limit_choices_to=models.Q(('company_type__contains', 'Supplier')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.company', verbose_name='Supplier'),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sales.inquiry', verbose_name='Inquiry'),
        ),
        migrations.CreateModel(
            name='OrderConfirmation',
            fields=[
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='confirmation', serialize=False, to='sales.quotation')),
                ('no', models.CharField(max_length=16, null=True, unique=True, verbose_name='No')),
                ('note', models.CharField(max_length=140, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='request', serialize=False, to='sales.project')),
                ('no', models.CharField(max_length=16, null=True, unique=True, verbose_name='No')),
                ('customer_ref', models.CharField(max_length=140, verbose_name='Customer Reference')),
                ('request_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency')),
                ('customer', models.ForeignKey(limit_choices_to=models.Q(('company_type__contains', 'Customer')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.company', verbose_name='Customer')),
                ('maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.maker', verbose_name='Maker')),
                ('maker_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='parts.makertype', verbose_name='Maker Type')),
                ('person_in_contact', models.ForeignKey(limit_choices_to=models.Q(('company__company_type__contains', 'Customer')), null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.contact', verbose_name='Person in Contact')),
                ('vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.vessel', verbose_name='Vessel')),
            ],
        ),
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='sales.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='project',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_responsible', to=settings.AUTH_USER_MODEL, verbose_name='Responsible'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiry', to='sales.project'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.project'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.project'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='sales.inquiry'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order', to='sales.project'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sales.purchaseorder'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='parts',
            field=models.ManyToManyField(related_name='delivery', to='sales.purchaseorderpart'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='inquiry_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='sales.inquirypart', verbose_name='Inquiry Part'),
        ),
        migrations.AddField(
            model_name='quotationpart',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sales.quotation', verbose_name='Quotation'),
        ),
        migrations.AddField(
            model_name='purchaseorderpart',
            name='quotation_part',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='sales.quotationpart'),
        ),
        migrations.AddField(
            model_name='requestpart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.part', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='inquirypart',
            name='request_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='sales.requestpart', verbose_name='Request Part'),
        ),
        migrations.AddField(
            model_name='deliverycustoms',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='deliveryinsurance',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='deliverypacking',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='deliverytax',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='deliverytransportation',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='order_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='sales.orderconfirmation'),
        ),
        migrations.CreateModel(
            name='OrderNotConfirmation',
            fields=[
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notconfirmation', serialize=False, to='sales.quotation')),
                ('no', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='No')),
                ('delievery_delay', models.PositiveIntegerField(default=1, verbose_name='Delivered Delay')),
                ('delivery_process_type', models.CharField(choices=[('email', 'By Email'), ('phone', 'By Phone'), ('verbal', 'Verbal')], default='email', max_length=6, verbose_name='Delivery Process Type')),
                ('customer_reaction', models.CharField(choices=[('OS', 'Optimistic and Satisfied'), ('HU', 'Harsh and Unsatisfied'), ('CN', 'Calm and Normal')], default='OS', max_length=6, verbose_name='Customer Reaction')),
                ('final_decision', models.BooleanField(choices=[(True, 'Yes, order will not be fulfilled'), (False, 'No, order pending')], default=False, verbose_name='Final Decision')),
                ('suggestion', models.TextField(null=True, verbose_name='Suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('reason_choices', models.ManyToManyField(to='sales.reason')),
            ],
        ),
        migrations.AddField(
            model_name='requestpart',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='sales.request', verbose_name='Request'),
        ),
        migrations.AlterUniqueTogether(
            name='inquiry',
            unique_together={('project', 'supplier')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderpart',
            unique_together={('purchase_order', 'quotation_part')},
        ),
        migrations.AlterUniqueTogether(
            name='inquirypart',
            unique_together={('inquiry', 'request_part')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('order_confirmation', 'inquiry')},
        ),
        migrations.AlterUniqueTogether(
            name='requestpart',
            unique_together={('request', 'part')},
        ),
    ]
