# Generated by Django 5.0.4 on 2025-08-18 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('beta_hr', '0001_initial'),
        ('beta_profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='beta_profile.currency'),
        ),
        migrations.AddField(
            model_name='thecompany',
            name='updated_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beta_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='the_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta_bank_accounts', to='beta_hr.thecompany'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('currency', 'iban')},
        ),
    ]
